services:
  - type: web
    name: renegociacao-boletos-ixc
    runtime: node
    buildCommand: pnpm build
    startCommand: pnpm run start
    envVars:
      - key: IXC_BASE_URL
        sync: false
      - key: IXC_TOKEN
        sync: false
